### ISSUE TITLE
02/03 - Tasks - feature/authenticationAndRegistration

### ISSUE THREAD

**Issue by antoniodecastroalves** [antoniodecastroalves/appgobarber#3]
Tasks - Authentication and registration

- [x] Input & Button
- [x] Authentication screen
- [x] Registration screen
- [x] Integrating Unform
- [x] Usability in forms
- [x] Focus and fill
- [x] Validation of forms

**Comment by antoniodecastroalves** [comment]
### Task accomplished!

Input & Button, Finished!

**Comment by antoniodecastroalves** [comment]
### Task accomplished!

Authentication screen, Finished!

**Comment by antoniodecastroalves** [comment]
### Task accomplished!
Registration screen, Finished!

**Comment by antoniodecastroalves** [comment]
### Task accomplished!
Integrating Unform, Finished!

**Comment by antoniodecastroalves** [comment]
### Task accomplished!
Usability in forms, Finished!

**Comment by antoniodecastroalves** [comment]
### Task accomplished!

Focus and fill, Finished!

**Comment by antoniodecastroalves** [comment]
### Task accomplished!
Validation of forms, Finished!
